# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cyrillic = {
    pname = "cyrillic";
    version = "86186af29eed2af1a069f9e36140d116a2765c80";
    src = fetchFromGitHub {
      owner = "nativerv";
      repo = "cyrillic.nvim";
      rev = "86186af29eed2af1a069f9e36140d116a2765c80";
      fetchSubmodules = false;
      sha256 = "sha256-B2NjvaKJbkih8HLgFAYVqmTuSKAj7XrCBPVoVpYCXXE=";
    };
    date = "2023-07-07";
  };
  heirline-components = {
    pname = "heirline-components";
    version = "5ea9a16286c01b7c36d58c91903d1f8ff0b7ddeb";
    src = fetchFromGitHub {
      owner = "Zeioth";
      repo = "heirline-components.nvim";
      rev = "5ea9a16286c01b7c36d58c91903d1f8ff0b7ddeb";
      fetchSubmodules = false;
      sha256 = "sha256-M86mP8Xr7tIFi9mM8icHWIzbWTR3W2xdSgzXhxNLMj4=";
    };
    date = "2026-02-25";
  };
  helium = {
    pname = "helium";
    version = "0.9.4.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.9.4.1/helium-0.9.4.1-x86_64_linux.tar.xz";
      sha256 = "sha256-qXuDUtank46O87jASxczmVMk0iD4JaZi2j9LSBe9VCM=";
    };
  };
  impermanence = {
    pname = "impermanence";
    version = "7b1d382faf603b6d264f58627330f9faa5cba149";
    src = fetchgit {
      url = "https://github.com/nix-community/impermanence";
      rev = "7b1d382faf603b6d264f58627330f9faa5cba149";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-03+JxvzmfwRu+5JafM0DLbxgHttOQZkUtDWBmeUkN8Y=";
    };
    date = "2026-01-27";
  };
  neorg-conceal-wrap = {
    pname = "neorg-conceal-wrap";
    version = "447a76e4abf07ccc5eeb8cc3ee5fae241b434f5a";
    src = fetchFromGitHub {
      owner = "benlubas";
      repo = "neorg-conceal-wrap";
      rev = "447a76e4abf07ccc5eeb8cc3ee5fae241b434f5a";
      fetchSubmodules = false;
      sha256 = "sha256-nEYuC5bM+VLSvBscpOC3EWwyVWzTPWDvv1o4tAzHzVU=";
    };
    date = "2025-10-17";
  };
  neorg-interim-ls = {
    pname = "neorg-interim-ls";
    version = "e2f86982ba5857ed5581ff5814edd57b5c2c67e0";
    src = fetchFromGitHub {
      owner = "benlubas";
      repo = "neorg-interim-ls";
      rev = "e2f86982ba5857ed5581ff5814edd57b5c2c67e0";
      fetchSubmodules = false;
      sha256 = "sha256-EdKEaxdme4tODtoJv8Yw/x3YtQoDLK0pmTT7xgE1LYQ=";
    };
    date = "2025-10-16";
  };
  neorg-query = {
    pname = "neorg-query";
    version = "e32b2dec08ec5a3ac3c7b0b4a500343886816e85";
    src = fetchFromGitHub {
      owner = "benlubas";
      repo = "neorg-query";
      rev = "e32b2dec08ec5a3ac3c7b0b4a500343886816e85";
      fetchSubmodules = false;
      sha256 = "sha256-jL5oMviGGKo9WgIPSFY3bBNmGuTjpUp+TPO4qW5NGlw=";
    };
    date = "2025-07-12";
  };
  nixos-hardware = {
    pname = "nixos-hardware";
    version = "41c6b421bdc301b2624486e11905c9af7b8ec68e";
    src = fetchgit {
      url = "https://github.com/nixos/nixos-hardware";
      rev = "41c6b421bdc301b2624486e11905c9af7b8ec68e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-qwcDBtrRvJbrrnv1lf/pREQi8t2hWZxVAyeMo7/E9sw=";
    };
    date = "2026-02-24";
  };
  nixos-wsl = {
    pname = "nixos-wsl";
    version = "379d20c55f552e91fb9f3f0382e4a97d3f452943";
    src = fetchgit {
      url = "https://github.com/nix-community/NixOS-WSL";
      rev = "379d20c55f552e91fb9f3f0382e4a97d3f452943";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-vA5hocvdGhr+jfBN7A7ogeZqIz2qx01EixXwdVsQcnE=";
    };
    date = "2026-02-20";
  };
  noctalia-dev = {
    pname = "noctalia-dev";
    version = "5137c5efcac31d9aee6952b99f1dcaec9966fe21";
    src = fetchgit {
      url = "https://github.com/noctalia-dev/noctalia-shell";
      rev = "5137c5efcac31d9aee6952b99f1dcaec9966fe21";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-M3U3DdQo/5G88ULedS8BkafiXYL1NyIEer9YL4P9fxQ=";
    };
    date = "2026-02-26";
  };
  sops-nix = {
    pname = "sops-nix";
    version = "334daa7c273dd8bf7a0cd370e4e16022b64e55e9";
    src = fetchgit {
      url = "https://github.com/Mic92/sops-nix";
      rev = "334daa7c273dd8bf7a0cd370e4e16022b64e55e9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-/wA0OaH6kZ/pFA+nXR/tvg5oupOmEDmMS5us79JT60o=";
    };
    date = "2026-02-25";
  };
}
