# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cyrillic = {
    pname = "cyrillic";
    version = "86186af29eed2af1a069f9e36140d116a2765c80";
    src = fetchFromGitHub {
      owner = "nativerv";
      repo = "cyrillic.nvim";
      rev = "86186af29eed2af1a069f9e36140d116a2765c80";
      fetchSubmodules = false;
      sha256 = "sha256-B2NjvaKJbkih8HLgFAYVqmTuSKAj7XrCBPVoVpYCXXE=";
    };
    date = "2023-07-07";
  };
  heirline-components = {
    pname = "heirline-components";
    version = "5ea9a16286c01b7c36d58c91903d1f8ff0b7ddeb";
    src = fetchFromGitHub {
      owner = "Zeioth";
      repo = "heirline-components.nvim";
      rev = "5ea9a16286c01b7c36d58c91903d1f8ff0b7ddeb";
      fetchSubmodules = false;
      sha256 = "sha256-M86mP8Xr7tIFi9mM8icHWIzbWTR3W2xdSgzXhxNLMj4=";
    };
    date = "2026-02-25";
  };
  helium = {
    pname = "helium";
    version = "0.10.2.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.10.2.1/helium-0.10.2.1-x86_64_linux.tar.xz";
      sha256 = "sha256-lq2ckkH/n4AoVwYg7uUO6ZYO4pcLINwKGxrv0uXdMuE=";
    };
  };
  impermanence = {
    pname = "impermanence";
    version = "7b1d382faf603b6d264f58627330f9faa5cba149";
    src = fetchgit {
      url = "https://github.com/nix-community/impermanence";
      rev = "7b1d382faf603b6d264f58627330f9faa5cba149";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-03+JxvzmfwRu+5JafM0DLbxgHttOQZkUtDWBmeUkN8Y=";
    };
    date = "2026-01-27";
  };
  neorg-conceal-wrap = {
    pname = "neorg-conceal-wrap";
    version = "447a76e4abf07ccc5eeb8cc3ee5fae241b434f5a";
    src = fetchFromGitHub {
      owner = "benlubas";
      repo = "neorg-conceal-wrap";
      rev = "447a76e4abf07ccc5eeb8cc3ee5fae241b434f5a";
      fetchSubmodules = false;
      sha256 = "sha256-nEYuC5bM+VLSvBscpOC3EWwyVWzTPWDvv1o4tAzHzVU=";
    };
    date = "2025-10-17";
  };
  neorg-interim-ls = {
    pname = "neorg-interim-ls";
    version = "e2f86982ba5857ed5581ff5814edd57b5c2c67e0";
    src = fetchFromGitHub {
      owner = "benlubas";
      repo = "neorg-interim-ls";
      rev = "e2f86982ba5857ed5581ff5814edd57b5c2c67e0";
      fetchSubmodules = false;
      sha256 = "sha256-EdKEaxdme4tODtoJv8Yw/x3YtQoDLK0pmTT7xgE1LYQ=";
    };
    date = "2025-10-16";
  };
  neorg-query = {
    pname = "neorg-query";
    version = "e32b2dec08ec5a3ac3c7b0b4a500343886816e85";
    src = fetchFromGitHub {
      owner = "benlubas";
      repo = "neorg-query";
      rev = "e32b2dec08ec5a3ac3c7b0b4a500343886816e85";
      fetchSubmodules = false;
      sha256 = "sha256-jL5oMviGGKo9WgIPSFY3bBNmGuTjpUp+TPO4qW5NGlw=";
    };
    date = "2025-07-12";
  };
  nix-minecraft = {
    pname = "nix-minecraft";
    version = "4d744dff3d8e0d9e7f85e06244ad353bdcf424ff";
    src = fetchgit {
      url = "https://github.com/Infinidoge/nix-minecraft";
      rev = "4d744dff3d8e0d9e7f85e06244ad353bdcf424ff";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-GvveRb/AiCb/dKXculKiNiAMW4CXMPwpeyi6c/S/a7o=";
    };
    date = "2026-03-11";
  };
  nixos-hardware = {
    pname = "nixos-hardware";
    version = "3966ce987e1a9a164205ac8259a5fe8a64528f72";
    src = fetchgit {
      url = "https://github.com/nixos/nixos-hardware";
      rev = "3966ce987e1a9a164205ac8259a5fe8a64528f72";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-mUJxsNOrBMNOUJzN0pfdVJ1r2pxeqm9gI/yIKXzVVbk=";
    };
    date = "2026-03-08";
  };
  nixos-wsl = {
    pname = "nixos-wsl";
    version = "be894604b2aa2184c0b3d3b44995acd0da14dc0c";
    src = fetchgit {
      url = "https://github.com/nix-community/NixOS-WSL";
      rev = "be894604b2aa2184c0b3d3b44995acd0da14dc0c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-sm6OpWZuoDwR53KNlsY482YOoHFWlWYwt0wHmqLkRGE=";
    };
    date = "2026-03-01";
  };
  noctalia-dev = {
    pname = "noctalia-dev";
    version = "786ca2c80f4ffa6b6cd4bd7f7cc68c972b0ee970";
    src = fetchgit {
      url = "https://github.com/noctalia-dev/noctalia-shell";
      rev = "786ca2c80f4ffa6b6cd4bd7f7cc68c972b0ee970";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-OWnfCulMgB0xodh1/y8J6O5J3ijyhVfWZwt6D0QrLIs=";
    };
    date = "2026-03-13";
  };
  noctalia-qs = {
    pname = "noctalia-qs";
    version = "d5209a6b5fe8c6dff8d530e820c96f09830011e3";
    src = fetchgit {
      url = "https://github.com/noctalia-dev/noctalia-qs";
      rev = "d5209a6b5fe8c6dff8d530e820c96f09830011e3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-pK01O5J9ogI4rVtDI+PVxckaXqpYZ4uthY0vgVWdyl8=";
    };
    date = "2026-03-11";
  };
  sops-nix = {
    pname = "sops-nix";
    version = "d1ff3b1034d5bab5d7d8086a7803c5a5968cd784";
    src = fetchgit {
      url = "https://github.com/Mic92/sops-nix";
      rev = "d1ff3b1034d5bab5d7d8086a7803c5a5968cd784";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-M3zEnq9OElB7zqc+mjgPlByPm1O5t2fbUrH3t/Hm5Ag=";
    };
    date = "2026-03-09";
  };
}
