# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  adifox = {
    pname = "adifox";
    version = "c063db1fe2c6b85365abc81d0367c14b63767a0c";
    src = fetchgit {
      url = "https://github.com/NotAShelf/adifox";
      rev = "c063db1fe2c6b85365abc81d0367c14b63767a0c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-1YPdderju+1fFf5P3CnD/SSP6P8kSLE0yykEPUJMQvQ=";
    };
    date = "2026-02-07";
  };
  adios = {
    pname = "adios";
    version = "6a54071689ec9ec784a16e4eec8ddb864eca2982";
    src = fetchgit {
      url = "https://github.com/adisbladis/adios";
      rev = "6a54071689ec9ec784a16e4eec8ddb864eca2982";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NshyMZYZwjKMLKEX0eDf9Fcekq8MFNFk02wW5knzlZU=";
    };
    date = "2026-02-27";
  };
  cyrillic = {
    pname = "cyrillic";
    version = "86186af29eed2af1a069f9e36140d116a2765c80";
    src = fetchFromGitHub {
      owner = "nativerv";
      repo = "cyrillic.nvim";
      rev = "86186af29eed2af1a069f9e36140d116a2765c80";
      fetchSubmodules = false;
      sha256 = "sha256-B2NjvaKJbkih8HLgFAYVqmTuSKAj7XrCBPVoVpYCXXE=";
    };
    date = "2023-07-07";
  };
  heirline-components = {
    pname = "heirline-components";
    version = "5ea9a16286c01b7c36d58c91903d1f8ff0b7ddeb";
    src = fetchFromGitHub {
      owner = "Zeioth";
      repo = "heirline-components.nvim";
      rev = "5ea9a16286c01b7c36d58c91903d1f8ff0b7ddeb";
      fetchSubmodules = false;
      sha256 = "sha256-M86mP8Xr7tIFi9mM8icHWIzbWTR3W2xdSgzXhxNLMj4=";
    };
    date = "2026-02-25";
  };
  helium = {
    pname = "helium";
    version = "0.10.7.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.10.7.1/helium-0.10.7.1-x86_64_linux.tar.xz";
      sha256 = "sha256-ZHziopdl8ClZQJUHXtIIb9ok/flZoixMdlLMKf5HUUo=";
    };
  };
  impermanence = {
    pname = "impermanence";
    version = "7b1d382faf603b6d264f58627330f9faa5cba149";
    src = fetchgit {
      url = "https://github.com/nix-community/impermanence";
      rev = "7b1d382faf603b6d264f58627330f9faa5cba149";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-03+JxvzmfwRu+5JafM0DLbxgHttOQZkUtDWBmeUkN8Y=";
    };
    date = "2026-01-27";
  };
  neorg-conceal-wrap = {
    pname = "neorg-conceal-wrap";
    version = "447a76e4abf07ccc5eeb8cc3ee5fae241b434f5a";
    src = fetchFromGitHub {
      owner = "benlubas";
      repo = "neorg-conceal-wrap";
      rev = "447a76e4abf07ccc5eeb8cc3ee5fae241b434f5a";
      fetchSubmodules = false;
      sha256 = "sha256-nEYuC5bM+VLSvBscpOC3EWwyVWzTPWDvv1o4tAzHzVU=";
    };
    date = "2025-10-17";
  };
  neorg-interim-ls = {
    pname = "neorg-interim-ls";
    version = "e2f86982ba5857ed5581ff5814edd57b5c2c67e0";
    src = fetchFromGitHub {
      owner = "benlubas";
      repo = "neorg-interim-ls";
      rev = "e2f86982ba5857ed5581ff5814edd57b5c2c67e0";
      fetchSubmodules = false;
      sha256 = "sha256-EdKEaxdme4tODtoJv8Yw/x3YtQoDLK0pmTT7xgE1LYQ=";
    };
    date = "2025-10-16";
  };
  neorg-query = {
    pname = "neorg-query";
    version = "64955f82bf6107d8ee05ce9c44bb40edd024b601";
    src = fetchFromGitHub {
      owner = "benlubas";
      repo = "neorg-query";
      rev = "64955f82bf6107d8ee05ce9c44bb40edd024b601";
      fetchSubmodules = false;
      sha256 = "sha256-5qmbZbM0A5mZ5OxxeruNuS9o8FfJymIEHPnHwwxQ5FQ=";
    };
    date = "2026-03-23";
  };
  nix-minecraft = {
    pname = "nix-minecraft";
    version = "1ee061a6a553b796504087fc172a536381c5ffe4";
    src = fetchgit {
      url = "https://github.com/Infinidoge/nix-minecraft";
      rev = "1ee061a6a553b796504087fc172a536381c5ffe4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0BmAweYRGLnfDtngAM//GeinbTUi3o3Tlp2U1DAH6Ck=";
    };
    date = "2026-03-29";
  };
  nixos-hardware = {
    pname = "nixos-hardware";
    version = "b8f81636927f1af0cca812d22c876bad0a883ccd";
    src = fetchgit {
      url = "https://github.com/nixos/nixos-hardware";
      rev = "b8f81636927f1af0cca812d22c876bad0a883ccd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-qogBiYFq8hZusDPeeKRqzelBAhZvREc7Cl+qlewGUCg=";
    };
    date = "2026-03-29";
  };
  nixos-wsl = {
    pname = "nixos-wsl";
    version = "fd0eae98d1ecee31024271f8d64676250a386ee7";
    src = fetchgit {
      url = "https://github.com/nix-community/NixOS-WSL";
      rev = "fd0eae98d1ecee31024271f8d64676250a386ee7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-VzcOcE0LLpEnyoxLuMuptZ9ZWCkSBn99bTgEQoz5Viw=";
    };
    date = "2026-03-19";
  };
  noctalia-dev = {
    pname = "noctalia-dev";
    version = "62f55f54de5981d64090baabdf2ac3256178bcdc";
    src = fetchgit {
      url = "https://github.com/noctalia-dev/noctalia-shell";
      rev = "62f55f54de5981d64090baabdf2ac3256178bcdc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-TB4HOlJwZ+w/8Jpjsga482IpDmLsekbbDGwVKLAUFWM=";
    };
    date = "2026-03-30";
  };
  noctalia-qs = {
    pname = "noctalia-qs";
    version = "0dbcb65548445dba2a8b095a9cd322bbb925225a";
    src = fetchgit {
      url = "https://github.com/noctalia-dev/noctalia-qs";
      rev = "0dbcb65548445dba2a8b095a9cd322bbb925225a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-RAjED7vBf5qmvwZD5Btwq397zJep2s2nKBih63Wh43M=";
    };
    date = "2026-03-30";
  };
  sops-nix = {
    pname = "sops-nix";
    version = "8adb84861fe70e131d44e1e33c426a51e2e0bfa5";
    src = fetchgit {
      url = "https://github.com/Mic92/sops-nix";
      rev = "8adb84861fe70e131d44e1e33c426a51e2e0bfa5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-D+tgywBHldTc0klWCIC49+6Zlp57Y4GGwxP1CqfxZrY=";
    };
    date = "2026-03-29";
  };
}
